[package]
name = "jupiter_arb_quote_self"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jupiter-aggregator = { path = "../Jupiter-lib"}
tokio = "1"
solana-sdk = "1.10"
spl-token = "3"
